services:
  postgres:
    image: postgres:15-alpine
    container_name: nestjs_postgres
    environment:
      POSTGRES_DB: nestjs_crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=nestjs_crud
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - nestjs_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:

networks:
  nestjs_network:
    driver: bridge 